# Generated by Django 4.2 on 2023-04-30 02:43

from django.db import migrations, models
import zach_test.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0002_document_delete_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document2",
            field=models.FileField(
                default="SOME STRING",
                upload_to="documents/%Y/%m/%d",
                validators=[zach_test.validators.validate_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="document", name="json_data", field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                upload_to="documents/%Y/%m/%d",
                validators=[zach_test.validators.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
