# Generated by Django 4.2 on 2023-05-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0003_document_document2_document_json_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_desc", models.CharField(blank=True, max_length=255)),
                ("period", models.FloatField()),
                ("n_forecasts", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="document", name="description",),
        migrations.RemoveField(model_name="document", name="document2",),
        migrations.AddField(
            model_name="document",
            name="if_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zach_test.task",
            ),
        ),
    ]
