# Generated by Django 4.2 on 2023-05-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0004_task_remove_document_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="task",
            field=models.ForeignKey(
                default="string",
                on_delete=django.db.models.deletion.CASCADE,
                to="zach_test.task",
            ),
        ),
    ]
