# Generated by Django 4.2.1 on 2023-05-06 06:24

from django.db import migrations, models
import django.db.models.deletion
import zach_test.models
import zach_test.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_desc", models.CharField(blank=True, max_length=255, null=True)),
                ("period", models.FloatField(null=True)),
                ("n_forecasts", models.IntegerField(null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("description", models.CharField(blank=True, max_length=255)),
                ("if_test", models.BooleanField(default=True, null=True)),
                (
                    "document",
                    models.FileField(
                        null=True,
                        upload_to=zach_test.models.document_upload_path,
                        validators=[zach_test.validators.validate_file_extension],
                    ),
                ),
                (
                    "document2",
                    models.FileField(
                        null=True,
                        upload_to=None,
                        validators=[zach_test.validators.validate_file_extension],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("json_data", models.JSONField(null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("fname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("funits", models.CharField(blank=True, max_length=255, null=True)),
                ("fvector_size", models.IntegerField(null=True)),
                ("flength", models.IntegerField(null=True)),
                ("fsampling_period", models.FloatField(null=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=zach_test.models.metrics_upload_path
                    ),
                ),
                (
                    "solution",
                    models.FileField(
                        null=True, upload_to=zach_test.models.metrics_upload_path
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zach_test.task",
                    ),
                ),
            ],
        ),
    ]
