# Generated by Django 4.2 on 2023-05-02 16:53

from django.db import migrations, models
import django.db.models.deletion
import zach_test.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_desc", models.CharField(blank=True, max_length=255)),
                ("period", models.FloatField()),
                ("n_forecasts", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("if_test", models.BooleanField(default=False)),
                (
                    "document",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d",
                        validators=[zach_test.validators.validate_file_extension],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("json_data", models.JSONField(null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zach_test.task",
                    ),
                ),
            ],
        ),
    ]
