# Generated by Django 4.2 on 2023-05-02 18:57

from django.db import migrations, models
import zach_test.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                null=True,
                upload_to="documents/%Y/%m/%d",
                validators=[zach_test.validators.validate_file_extension],
            ),
        ),
    ]
