# Generated by Django 4.2 on 2023-05-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="task_desc", field=models.CharField(max_length=255),
        ),
    ]
