# Generated by Django 4.2.1 on 2023-05-06 04:03

from django.db import migrations, models
import zach_test.models


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="image",
            field=models.ImageField(
                null=True, upload_to=zach_test.models.metrics_upload_path
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="solution",
            field=models.FileField(
                null=True, upload_to=zach_test.models.metrics_upload_path
            ),
        ),
    ]
