# Generated by Django 4.2.1 on 2023-05-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
