# Generated by Django 4.2 on 2023-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0002_alter_document_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
