# Generated by Django 4.2.1 on 2023-05-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0002_document_file_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="document2",),
    ]
