# Generated by Django 4.2.1 on 2023-05-05 05:07

from django.db import migrations, models
import zach_test.models
import zach_test.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0003_remove_document_document2"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document2",
            field=models.FileField(
                default=None,
                null=True,
                upload_to=zach_test.models.document_upload_path,
                validators=[zach_test.validators.validate_file_extension],
            ),
        ),
    ]
