# Generated by Django 4.2 on 2023-05-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0003_alter_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
