# Generated by Django 4.2 on 2023-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0004_alter_task_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="n_forecasts", field=models.IntegerField(null=True),
        ),
    ]
