# Generated by Django 4.2 on 2023-05-03 04:53

from django.db import migrations, models
import zach_test.models
import zach_test.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zach_test", "0005_remove_document_description_document_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                null=True,
                upload_to=zach_test.models.document_upload_path,
                validators=[zach_test.validators.validate_file_extension],
            ),
        ),
    ]
